window.GAME_CONTENT = {
  species: [
    {
      id: "golden-guppy",
      species: "Guppy dore",
      cost: 0,
      sellPrice: 0,
      rarity: "Commun",
      income: 6,
      growthHours: 96,
      colors: ["#ffd166", "#ff9d42"],
      sizeScale: 0.82,
      sprite: {
        file: "./assets/fish/golden-guppy.png",
        w: 214,
        h: 132,
        tailSplit: 72,
        tailJoint: 68,
        direction: -1,
      },
      biome: "Lagon",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 22,
      temperatureMax: 26,
      oxygenMin: 42,
      phMin: 6.8,
      phMax: 7.8,
      adultSizeCm: 4,
      lifespanWeeks: 26,
      lifespanCycles: 28,
      preferredPlantId: "vallis-emerald",
      behaviorProfile: {
        lane: "upper-mid",
        sociability: "shoaling",
        pace: "light",
        hoverChance: 0.14,
        inspectChance: 0.18,
        cruiseChance: 0.68,
      },
      description: "Petit poisson sociable parfait pour lancer un elevage vivant.",
    },
    {
      id: "sun-cory",
      species: "Cory solaire",
      cost: 0,
      sellPrice: 0,
      rarity: "Peu commun",
      income: 10,
      growthHours: 132,
      colors: ["#ffb26b", "#f96d4a"],
      sizeScale: 1,
      sprite: {
        file: "./assets/fish/sun-cory.png",
        w: 283,
        h: 146,
        tailSplit: 74,
        tailJoint: 69,
        direction: -1,
      },
      biome: "Riviere chaude",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 24,
      temperatureMax: 28,
      oxygenMin: 48,
      phMin: 6.6,
      phMax: 7.4,
      adultSizeCm: 6,
      lifespanWeeks: 52,
      lifespanCycles: 31,
      preferredPlantId: "anubia-bronze",
      behaviorProfile: {
        lane: "bottom",
        sociability: "shoaling",
        pace: "slow",
        hoverChance: 0.34,
        inspectChance: 0.38,
        cruiseChance: 0.28,
      },
      description: "Un poisson de fond qui aide a garder un bac calme et stable.",
    },
    {
      id: "moon-betta",
      species: "Betta lunaire",
      cost: 0,
      sellPrice: 0,
      rarity: "Rare",
      income: 12,
      growthHours: 168,
      colors: ["#7be0c0", "#45aaf2"],
      sizeScale: 1.45,
      sprite: {
        file: "./assets/fish/moon-betta.png",
        w: 236,
        h: 209,
        tailSplit: 54,
        tailJoint: 49,
        direction: -1,
      },
      biome: "Jardin nocturne",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 25,
      temperatureMax: 29,
      oxygenMin: 35,
      phMin: 6.2,
      phMax: 7.4,
      adultSizeCm: 7,
      lifespanWeeks: 78,
      lifespanCycles: 34,
      preferredPlantId: "lotus-rose",
      behaviorProfile: {
        lane: "upper",
        sociability: "solitary",
        pace: "slow",
        hoverChance: 0.42,
        inspectChance: 0.22,
        cruiseChance: 0.36,
      },
      description: "Un nageur de prestige qui attire les visiteurs du port.",
    },
    {
      id: "coral-clown",
      species: "Clown corallien",
      cost: 0,
      sellPrice: 0,
      rarity: "Peu commun",
      income: 11,
      growthHours: 144,
      colors: ["#ff9a5a", "#ffffff"],
      sizeScale: 0.92,
      sprite: {
        file: "./assets/fish/coral-clown.png",
        w: 175,
        h: 111,
        tailSplit: 73,
        tailJoint: 68,
        direction: -1,
      },
      biome: "Recif",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 24,
      temperatureMax: 27,
      oxygenMin: 55,
      phMin: 6.8,
      phMax: 7.6,
      adultSizeCm: 8,
      lifespanWeeks: 62,
      lifespanCycles: 30,
      preferredPlantId: "anubia-bronze",
      behaviorProfile: {
        lane: "mid",
        sociability: "paired",
        pace: "balanced",
        hoverChance: 0.2,
        inspectChance: 0.34,
        cruiseChance: 0.46,
      },
      description: "Une star chaleureuse ideale pour les aquariums lumineux.",
    },
    {
      id: "glass-tetra",
      species: "Tetra de verre",
      cost: 0,
      sellPrice: 0,
      rarity: "Rare",
      income: 13,
      growthHours: 156,
      colors: ["#d8f6ff", "#82cfff"],
      sizeScale: 0.72,
      sprite: {
        file: "./assets/fish/glass-tetra.png",
        w: 177,
        h: 104,
        tailSplit: 78,
        tailJoint: 73,
        direction: -1,
      },
      biome: "Riviere claire",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 21,
      temperatureMax: 24,
      oxygenMin: 62,
      phMin: 6.0,
      phMax: 7.2,
      adultSizeCm: 5,
      lifespanWeeks: 42,
      lifespanCycles: 27,
      preferredPlantId: "cabomba-feather",
      behaviorProfile: {
        lane: "mid",
        sociability: "shoaling",
        pace: "swift",
        hoverChance: 0.1,
        inspectChance: 0.18,
        cruiseChance: 0.72,
      },
      description: "Sa silhouette translucide donne une allure haut de gamme au bac.",
    },
    {
      id: "moss-koi",
      species: "Koi mousse",
      cost: 0,
      sellPrice: 0,
      rarity: "Rare",
      income: 15,
      growthHours: 192,
      colors: ["#f7e8b1", "#7abf6e"],
      sizeScale: 1.02,
      sprite: {
        file: "./assets/fish/moss-koi.png",
        w: 184,
        h: 96,
        tailSplit: 74,
        tailJoint: 69,
        direction: -1,
      },
      biome: "Jardin zen",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 20,
      temperatureMax: 24,
      oxygenMin: 58,
      phMin: 7.0,
      phMax: 8.0,
      adultSizeCm: 12,
      lifespanWeeks: 104,
      lifespanCycles: 36,
      preferredPlantId: "lotus-rose",
      behaviorProfile: {
        lane: "mid-low",
        sociability: "paired",
        pace: "slow",
        hoverChance: 0.28,
        inspectChance: 0.32,
        cruiseChance: 0.4,
      },
      description: "Un grand nageur calme qui renforce la valeur contemplative du recif.",
    },
    {
      id: "pearl-discus",
      species: "Discus perle",
      cost: 0,
      sellPrice: 0,
      rarity: "Epic",
      income: 17,
      growthHours: 216,
      colors: ["#ffe3f1", "#ffa0cc"],
      sizeScale: 1.18,
      sprite: {
        file: "./assets/fish/pearl-discus.png",
        w: 201,
        h: 123,
        tailSplit: 69,
        tailJoint: 64,
        direction: -1,
      },
      biome: "Lagune perlee",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 27,
      temperatureMax: 30,
      oxygenMin: 52,
      phMin: 6.0,
      phMax: 7.0,
      adultSizeCm: 15,
      lifespanWeeks: 96,
      lifespanCycles: 35,
      preferredPlantId: "anubia-bronze",
      behaviorProfile: {
        lane: "mid",
        sociability: "grouped",
        pace: "slow",
        hoverChance: 0.36,
        inspectChance: 0.24,
        cruiseChance: 0.4,
      },
      description: "Un disque raffine qui fait monter la reputation du gardien.",
    },
    {
      id: "reef-angel",
      species: "Ange de recif",
      cost: 0,
      sellPrice: 0,
      rarity: "Epic",
      income: 18,
      growthHours: 204,
      colors: ["#c5d8ff", "#5ed0c3"],
      sizeScale: 1.14,
      sprite: {
        file: "./assets/fish/reef-angel.png",
        w: 180,
        h: 141,
        tailSplit: 62,
        tailJoint: 57,
        direction: -1,
      },
      biome: "Recif royal",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 24,
      temperatureMax: 27,
      oxygenMin: 66,
      phMin: 6.4,
      phMax: 7.4,
      adultSizeCm: 14,
      lifespanWeeks: 88,
      lifespanCycles: 33,
      preferredPlantId: "kelp-spiral",
      behaviorProfile: {
        lane: "mid-high",
        sociability: "territorial",
        pace: "balanced",
        hoverChance: 0.24,
        inspectChance: 0.3,
        cruiseChance: 0.46,
      },
      description: "Une vedette majestueuse qui rapporte de belles perles.",
    },
    {
      id: "ember-rasbora",
      species: "Rasbora braise",
      cost: 0,
      sellPrice: 0,
      rarity: "Rare",
      income: 12,
      growthHours: 108,
      colors: ["#ff8d57", "#ffcf6c"],
      sizeScale: 0.62,
      sprite: {
        file: "./assets/fish/ember-rasbora.png",
        w: 177,
        h: 68,
        tailSplit: 79,
        tailJoint: 73,
        direction: -1,
      },
      biome: "Mangrove",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 23,
      temperatureMax: 27,
      oxygenMin: 50,
      phMin: 6.6,
      phMax: 7.6,
      adultSizeCm: 3,
      lifespanWeeks: 36,
      lifespanCycles: 29,
      preferredPlantId: "cabomba-feather",
      behaviorProfile: {
        lane: "upper-mid",
        sociability: "shoaling",
        pace: "swift",
        hoverChance: 0.08,
        inspectChance: 0.16,
        cruiseChance: 0.76,
      },
      description: "Un poisson vif qui donne du rythme a la scene principale.",
    },
    {
      id: "starlight-gourami",
      species: "Gourami stellaire",
      cost: 0,
      sellPrice: 0,
      rarity: "Epic",
      income: 19,
      growthHours: 228,
      colors: ["#c6c4ff", "#91f0e8"],
      sizeScale: 0.9,
      sprite: {
        file: "./assets/fish/starlight-gourami.png",
        w: 180,
        h: 110,
        tailSplit: 74,
        tailJoint: 69,
        direction: -1,
      },
      biome: "Ciel d'eau",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 25,
      temperatureMax: 28,
      oxygenMin: 46,
      phMin: 6.5,
      phMax: 7.5,
      adultSizeCm: 10,
      lifespanWeeks: 84,
      lifespanCycles: 32,
      preferredPlantId: "lotus-rose",
      behaviorProfile: {
        lane: "upper",
        sociability: "solitary",
        pace: "balanced",
        hoverChance: 0.3,
        inspectChance: 0.22,
        cruiseChance: 0.48,
      },
      description: "Ses reflets lumineux rendent chaque visite plus memorable.",
    },
  ],
  plants: [
    {
      id: "vallis-emerald",
      species: "Vallisneria emeraude",
      rarity: "Commun",
      biome: "Prairie tropicale",
      unlockLevel: 1,
      temperatureMin: 20,
      temperatureMax: 27,
      oxygenGeneration: 1.8,
      comfortBonus: 4,
      phMin: 6.5,
      phMax: 7.8,
      lightMin: 3,
      lightMax: 5,
      co2Need: 3.2,
      lifespanCycles: 34,
      fryProtection: 18,
      contestPresence: 8,
      sizeScale: 1.16,
      sprite: {
        file: "./assets/plants/vallis-emerald.png",
        w: 170,
        h: 252,
        displayHeight: 98,
        rootCut: 18,
        swayAngle: 4.8,
        swayDuration: 5.8,
      },
      description: "Une grande plante rubanee qui enrichit l'eau en oxygene.",
    },
    {
      id: "lotus-rose",
      species: "Lotus rose",
      rarity: "Peu commun",
      biome: "Mares chaudes",
      unlockLevel: 1,
      temperatureMin: 22,
      temperatureMax: 28,
      oxygenGeneration: 0.7,
      comfortBonus: 8,
      phMin: 6.2,
      phMax: 7.2,
      lightMin: 4,
      lightMax: 6,
      co2Need: 4.5,
      lifespanCycles: 29,
      fryProtection: 10,
      contestPresence: 15,
      sizeScale: 0.94,
      sprite: {
        file: "./assets/plants/lotus-rose.png",
        w: 163,
        h: 90,
        displayHeight: 58,
        rootCut: 12,
        swayAngle: 2.2,
        swayDuration: 6.6,
      },
      description: "Une fleur delicate qui adore les eaux stables et lumineuses.",
    },
    {
      id: "anubia-bronze",
      species: "Anubia bronze",
      rarity: "Peu commun",
      biome: "Sous-bois chaud",
      unlockLevel: 1,
      temperatureMin: 22,
      temperatureMax: 29,
      oxygenGeneration: 0.95,
      comfortBonus: 7,
      phMin: 6.0,
      phMax: 7.5,
      lightMin: 2,
      lightMax: 4,
      co2Need: 2.2,
      lifespanCycles: 36,
      fryProtection: 12,
      contestPresence: 9,
      sizeScale: 1,
      sprite: {
        file: "./assets/plants/anubia-bronze.png",
        w: 97,
        h: 181,
        displayHeight: 82,
        rootCut: 24,
        swayAngle: 2.8,
        swayDuration: 7.2,
      },
      description: "Une plante robuste, parfaite pour stabiliser un aquarium jeune.",
    },
    {
      id: "cabomba-feather",
      species: "Cabomba plume",
      rarity: "Rare",
      biome: "Riviere claire",
      unlockLevel: 1,
      temperatureMin: 18,
      temperatureMax: 25,
      oxygenGeneration: 1.55,
      comfortBonus: 3,
      phMin: 6.0,
      phMax: 7.0,
      lightMin: 4,
      lightMax: 6,
      co2Need: 5.6,
      lifespanCycles: 28,
      fryProtection: 20,
      contestPresence: 7,
      sizeScale: 1.06,
      sprite: {
        file: "./assets/plants/cabomba-feather.png",
        w: 137,
        h: 204,
        displayHeight: 90,
        rootCut: 16,
        swayAngle: 5.6,
        swayDuration: 5.1,
      },
      description: "Une tige legere et tres oxygenante qui ondule sans cesse.",
    },
    {
      id: "kelp-spiral",
      species: "Kelp spiral",
      rarity: "Rare",
      biome: "Lagune temperee",
      unlockLevel: 1,
      temperatureMin: 19,
      temperatureMax: 26,
      oxygenGeneration: 1.2,
      comfortBonus: 5,
      phMin: 6.4,
      phMax: 7.6,
      lightMin: 3,
      lightMax: 5,
      co2Need: 3.8,
      lifespanCycles: 31,
      fryProtection: 14,
      contestPresence: 13,
      sizeScale: 1.08,
      sprite: {
        file: "./assets/plants/kelp-spiral.png",
        w: 111,
        h: 198,
        displayHeight: 94,
        rootCut: 14,
        swayAngle: 6.4,
        swayDuration: 4.8,
      },
      description: "Une silhouette torsadee qui donne du relief et renouvelle l'oxygene.",
    },
  ],
  shopItems: [
    {
      id: "food-pack",
      name: "Granules marines",
      type: "food",
      amount: 6,
      cost: 28,
      tier: "Base",
      description: "Recharge 6 portions de nourriture premium.",
    },
    {
      id: "food-feast",
      name: "Banquet de plancton",
      type: "food",
      amount: 14,
      cost: 58,
      tier: "Confort",
      description: "Un stock plus rentable pour les aquariums qui grandissent.",
    },
    {
      id: "water-kit",
      name: "Kit de filtration",
      type: "water",
      amount: 20,
      cost: 36,
      tier: "Base",
      description: "Ajoute un kit de filtration pour un nettoyage renforce.",
    },
    {
      id: "water-premium",
      name: "Cycleur oceanique",
      type: "water",
      amount: 34,
      cost: 62,
      tier: "Premium",
      description: "Une maintenance haut de gamme pour les grands bacs.",
    },
    {
      id: "ph-up-tabs",
      name: "Pastilles pH+",
      type: "ph-up",
      amount: 4,
      cost: 32,
      tier: "Chimie",
      description: "Augmente legerement le pH du bac. Pack de 4 pastilles.",
    },
    {
      id: "ph-down-tabs",
      name: "Pastilles pH-",
      type: "ph-down",
      amount: 4,
      cost: 32,
      tier: "Chimie",
      description: "Baisse legerement le pH du bac. Pack de 4 pastilles.",
    },
    {
      id: "lamp-upgrade-2",
      name: "Lampe horticole II",
      type: "lamp",
      level: 2,
      cost: 74,
      tier: "Equipement",
      description: "Etend le reglage de luminosite jusqu'a 8 h d'exposition.",
    },
    {
      id: "lamp-upgrade-3",
      name: "Lampe horticole III",
      type: "lamp",
      level: 3,
      cost: 128,
      tier: "Equipement",
      description: "Etend le reglage de luminosite jusqu'a 10 h d'exposition.",
    },
    {
      id: "lamp-upgrade-4",
      name: "Lampe horticole IV",
      type: "lamp",
      level: 4,
      cost: 186,
      tier: "Equipement",
      description: "Etend le reglage de luminosite jusqu'a 12 h d'exposition.",
    },
    {
      id: "lamp-upgrade-5",
      name: "Lampe horticole V",
      type: "lamp",
      level: 5,
      cost: 248,
      tier: "Equipement",
      description: "Etend le reglage de luminosite jusqu'a 14 h d'exposition.",
    },
    {
      id: "co2-upgrade-2",
      name: "Diffuseur CO2 II",
      type: "co2",
      level: 2,
      cost: 82,
      tier: "Equipement",
      description: "Augmente la production maximale automatique de CO2 jusqu'au niveau 6.",
    },
    {
      id: "co2-upgrade-3",
      name: "Diffuseur CO2 III",
      type: "co2",
      level: 3,
      cost: 136,
      tier: "Equipement",
      description: "Augmente la production maximale automatique de CO2 jusqu'au niveau 8.",
    },
    {
      id: "co2-upgrade-4",
      name: "Diffuseur CO2 IV",
      type: "co2",
      level: 4,
      cost: 194,
      tier: "Equipement",
      description: "Augmente la production maximale automatique de CO2 jusqu'au niveau 10.",
    },
    {
      id: "co2-upgrade-5",
      name: "Diffuseur CO2 V",
      type: "co2",
      level: 5,
      cost: 256,
      tier: "Equipement",
      description: "Augmente la production maximale automatique de CO2 jusqu'au niveau 12.",
    },
    {
      id: "filter-upgrade-2",
      name: "Filtre II",
      type: "filter",
      level: 2,
      cost: 70,
      tier: "Equipement",
      description: "Reduit l'impact du cycle sur la qualite de l'eau de 8%.",
    },
    {
      id: "filter-upgrade-3",
      name: "Filtre III",
      type: "filter",
      level: 3,
      cost: 112,
      tier: "Equipement",
      description: "Reduit l'impact du cycle sur la qualite de l'eau de 10%.",
    },
    {
      id: "filter-upgrade-4",
      name: "Filtre IV",
      type: "filter",
      level: 4,
      cost: 164,
      tier: "Equipement",
      description: "Reduit l'impact du cycle sur la qualite de l'eau de 12%.",
    },
    {
      id: "filter-upgrade-5",
      name: "Filtre V",
      type: "filter",
      level: 5,
      cost: 224,
      tier: "Equipement",
      description: "Reduit l'impact du cycle sur la qualite de l'eau de 14%.",
    },
    {
      id: "plant-vallis-emerald",
      name: "Vallisneria emeraude",
      type: "plant",
      plantType: "vallis-emerald",
      cost: 58,
      tier: "Oxygenante",
      description: "Grande herbe souple pour les zones denses et oxygenees.",
    },
    {
      id: "plant-lotus-rose",
      name: "Lotus rose",
      type: "plant",
      plantType: "lotus-rose",
      cost: 72,
      tier: "Florale",
      description: "Une touche florale pour les bacs bien temperes.",
    },
    {
      id: "plant-anubia-bronze",
      name: "Anubia bronze",
      type: "plant",
      plantType: "anubia-bronze",
      cost: 68,
      tier: "Stable",
      description: "Une plante fiable qui supporte bien les aquariums communautaires.",
    },
    {
      id: "plant-cabomba-feather",
      name: "Cabomba plume",
      type: "plant",
      plantType: "cabomba-feather",
      cost: 88,
      tier: "Premium",
      description: "Plante plume tres oxygenante pour les bacs les plus sains.",
    },
    {
      id: "plant-kelp-spiral",
      name: "Kelp spiral",
      type: "plant",
      plantType: "kelp-spiral",
      cost: 96,
      tier: "Signature",
      description: "Une plante torsadee pour donner une silhouette forte au bac.",
    },
  ],
  communityPlayers: [
    {
      id: "naya",
      name: "Naya",
      aquarium: "Atelier des hippocampes",
      specialty: "Elevage zen",
      visitors: 128,
      mood: "Organise des visites guidees pour debutants.",
      gift: "food",
    },
    {
      id: "marin",
      name: "Marin",
      aquarium: "Courant saphir",
      specialty: "Plantes rares",
      visitors: 204,
      mood: "Collectionne des arches minieres et des coraux massifs.",
      gift: "coins",
    },
    {
      id: "thea",
      name: "Thea",
      aquarium: "Lagune de lune",
      specialty: "Poissons rares",
      visitors: 176,
      mood: "Partage souvent des astuces sur les bettas lunaires.",
      gift: "pearls",
    },
    {
      id: "sami",
      name: "Sami",
      aquarium: "Jardin abyssal",
      specialty: "Evenements",
      visitors: 149,
      mood: "Lance des mini-defis communautaires chaque semaine.",
      gift: "food",
    },
    {
      id: "eloi",
      name: "Eloi",
      aquarium: "Terrasse aux raies",
      specialty: "Collection tardive",
      visitors: 265,
      mood: "Met en scene les especes legendaires dans de grands bacs thematiques.",
      gift: "pearls",
    },
    {
      id: "mae",
      name: "Mae",
      aquarium: "Studio des lagunes",
      specialty: "Aesthetique",
      visitors: 188,
      mood: "Compose des bacs tres photographiques avec peu d'especes mais beaucoup de style.",
      gift: "coins",
    },
  ],
  events: [
    {
      id: "coral",
      name: "Maree des coraux",
      badge: "Evenement corallien",
      description:
        "Les visiteurs affluent pour admirer les aquariums les plus luxuriants. Les visites rapportent 25% de coquillages en plus.",
      visitBonusMultiplier: 1.25,
    },
    {
      id: "pearls",
      name: "Nuit des perles",
      badge: "Festival des perles",
      description:
        "Les poissons rares brillent davantage. Chaque recompense quotidienne donne des perles supplementaires.",
      dailyPearlsBonus: 6,
    },
    {
      id: "fry",
      name: "Fete des alevins",
      badge: "Saison des naissances",
      description:
        "Les tentatives de reproduction ont plus de succes et les jeunes poissons grandissent plus vite.",
      breedBonus: 0.18,
    },
    {
      id: "royal",
      name: "Salon royal",
      badge: "Semaine prestige",
      description:
        "Les especes epic et legendaires rapportent davantage de reputation et de coquillages.",
      rareIncomeBonus: 1.2,
    },
    {
      id: "flora",
      name: "Expo botanique",
      badge: "Expo botanique",
      description:
        "Les bacs riches en plantes naturelles gagnent plus de joie et de visiteurs pendant la semaine.",
      decorVisitorBonus: 6,
    },
    {
      id: "harbor",
      name: "Port en fete",
      badge: "Port en fete",
      description:
        "Les interactions communautaires sont mieux recompensees et les cadeaux sont plus frequents.",
      socialCoinsBonus: 12,
    },
  ],
  tips: [
    "Des poissons bien nourris et une eau propre augmentent naturellement les visites.",
    "Une belle selection de plantes rend ton aquarium plus memorable et plus vivant.",
    "Les especes rares donnent moins de revenus immediats mais tirent la progression sur la duree.",
    "Visiter souvent le port communautaire est une bonne source de recompenses et d'idees d'amenagement.",
    "Un bac qui raconte une histoire est souvent plus marquant qu'un simple empilement de raretes.",
    "La reproduction devient plus interessante une fois tes adultes bien stabilises.",
    "Les evenements sont parfaits pour faire tourner la meta sans casser l'economie.",
    "Le contenu saisonnier doit idealement recompenser la connexion reguliere sans punir l'absence.",
  ],
  missionPool: [
    {
      id: "feed-2",
      label: "Nourrir tes pensionnaires 2 fois",
      goal: 2,
      rewardCoins: 45,
      rewardPearls: 2,
      tracker: "feedCount",
    },
    {
      id: "feed-4",
      label: "Assurer 4 services de nourriture",
      goal: 4,
      rewardCoins: 82,
      rewardPearls: 4,
      tracker: "feedCount",
    },
    {
      id: "visit-2",
      label: "Visiter 2 aquariums communautaires",
      goal: 2,
      rewardCoins: 38,
      rewardPearls: 3,
      tracker: "visitCount",
    },
    {
      id: "visit-4",
      label: "Faire une tournee de 4 visites",
      goal: 4,
      rewardCoins: 88,
      rewardPearls: 5,
      tracker: "visitCount",
    },
    {
      id: "buy-1",
      label: "Acheter une ressource ou une deco",
      goal: 1,
      rewardCoins: 34,
      rewardPearls: 1,
      tracker: "purchaseCount",
    },
    {
      id: "buy-3",
      label: "Effectuer 3 achats dans la boutique",
      goal: 3,
      rewardCoins: 94,
      rewardPearls: 4,
      tracker: "purchaseCount",
    },
    {
      id: "clean-2",
      label: "Nettoyer l'eau 2 fois",
      goal: 2,
      rewardCoins: 52,
      rewardPearls: 2,
      tracker: "cleanCount",
    },
    {
      id: "oxygen-2",
      label: "Oxygener le bac 2 fois",
      goal: 2,
      rewardCoins: 44,
      rewardPearls: 2,
      tracker: "oxygenCount",
    },
    {
      id: "adopt-1",
      label: "Adopter un nouveau poisson",
      goal: 1,
      rewardCoins: 60,
      rewardPearls: 3,
      tracker: "adoptionCount",
    },
    {
      id: "breed-1",
      label: "Tenter une reproduction",
      goal: 1,
      rewardCoins: 66,
      rewardPearls: 4,
      tracker: "breedCount",
    },
    {
      id: "decor-1",
      label: "Installer une nouvelle deco",
      goal: 1,
      rewardCoins: 58,
      rewardPearls: 2,
      tracker: "decorateCount",
    },
    {
      id: "reward-1",
      label: "Recuperer la recompense du jour",
      goal: 1,
      rewardCoins: 32,
      rewardPearls: 2,
      tracker: "dailyRewardCount",
    },
  ],
  missionTrackers: [
    "feedCount",
    "visitCount",
    "purchaseCount",
    "cleanCount",
    "oxygenCount",
    "adoptionCount",
    "breedCount",
    "decorateCount",
    "dailyRewardCount",
  ],
  fishNames: {
    prefixes: ["Aster", "Nemo", "Kora", "Vega", "Lilo", "Nova", "Rubi", "Siro", "Iris", "Melo"],
    suffixes: ["bleu", "perle", "flot", "mousse", "sel", "corail", "aube", "brume", "ivoire", "lagon"],
    babies: ["Pixel", "Etoile", "Plume", "Bulle", "Luciole", "Mica", "Tide", "Pico", "Nacre", "Miro"],
  },
};
